#version: 2.1
#general:
#  working_directory: ~/project/mobile/companion_app_project/
#  build_dir: ~/project/mobile/companion_app_project/
  
#orbs:
# android: circleci/android@0.2.0

#jobs:
# build:
#   executor: android/android

#   steps:
#     - checkout
#     - run:
#         command: ./gradlew build

version: 2.1

general:
  working_directory: ~/project/mobile/companion_app_project/
  build_dir: ~/project/mobile/companion_app_project/
orbs:
  android: circleci/android@1.0.3

workflows:
  test:
    jobs:
      # This job uses the Android machine image by default
      - android/run-ui-tests:
          # Use pre-steps and post-steps if necessary
          # to execute custom steps before and afer any of the built-in steps
          system-image: system-images;android-29;default;x86