version: 2.1
general:
  working_directory: ~/project/mobile/companion_app_project/
  build_dir: ~/project/mobile/companion_app_project/
  
orbs:
 android: circleci/android@0.2.0

jobs:
 build:
   executor: android/android

   steps:
     - checkout
     - android/restore-gradle-cache
     - android/restore-build-cache
     - run:
         command: ./gradlew build
