version: 2.1
general:
  working_directory: ~/circlecimobile/companion_app_project/
  
orbs:
 android: circleci/android@0.2.0

jobs:
 build:
   executor: android/android

   steps:
     - checkout
     - run:
         command: ./gradlew build
